name: Update Resonite Shim

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Update Resonite.GameLibs
        run: ./.codex/update-resonite-shim.sh
      - name: Format
        run: |
          dotnet tool restore
          dotnet csharpier format Directory.Packages.props
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "⬆️ chore: update Resonite.GameLibs"
          branch: update-resonite-gamelibs
          title: "⬆️ chore: update Resonite.GameLibs"
          body: Update Resonite.GameLibs to latest version

